export default [{
  name: '正常开启',
  icon: '',
  value: 'compositor',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '正常开启',
      icon: '',
      value: '0',
      selectIndex: 0
    }, {
      name: '非法开启',
      icon: '',
      value: '1',
      selectIndex: 1
    }, {
      name: '关闭',
      icon: '',
      value: '2',
      selectIndex: 2
    }]
  }]
}, {
  name: '使用时间',
  icon: '',
  value: 'compositor',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '0~3小时',
      icon: '',
      value: '0',
      selectIndex: 0
    }, {
      name: '3~6小时',
      icon: '',
      value: '1',
      selectIndex: 1
    }, {
      name: '6~9小时',
      icon: '',
      value: '2',
      selectIndex: 2
    }, {
      name: '9~12小时',
      icon: '',
      value: '2',
      selectIndex: 2
    }, {
      name: '12小时以上',
      icon: '',
      value: '2',
      selectIndex: 2
    }]
  }]
}, {
  name: '电池电量',
  icon: '',
  value: 'compositor',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '20%以下',
      icon: '',
      value: '0',
      selectIndex: 0
    }, {
      name: '50%以下',
      icon: '',
      value: '1',
      selectIndex: 1
    }, {
      name: '50%以上',
      icon: '',
      value: '2',
      selectIndex: 2
    }]
  }]
}, {
  name: '流量',
  icon: '',
  value: 'compositor',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '100b',
      icon: '',
      value: '0',
      selectIndex: 0
    }, {
      name: '100kb',
      icon: '',
      value: '1',
      selectIndex: 1
    }, {
      name: '100mb',
      icon: '',
      value: '2',
      selectIndex: 2
    }]
  }]
}, ]
