export default [{
  name: '正常开启',
  icon: '',
  value: '',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '正常开启',
      icon: '',
      value: '1',
      selectIndex: 0
    }, {
      name: '非法开启',
      icon: '',
      value: '6',
      selectIndex: 1
    }, {
      name: '关闭',
      icon: '',
      value: '2',
      selectIndex: 2
    }]
  }]
}, {
  name: '使用时间',
  icon: '',
  value: '',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '0~3小时',
      icon: '',
      value: '0-3',
      selectIndex: 3
    }, {
      name: '3~6小时',
      icon: '',
      value: '3-6',
      selectIndex: 4
    }, {
      name: '6~9小时',
      icon: '',
      value: '6-9',
      selectIndex: 5
    }, {
      name: '9~12小时',
      icon: '',
      value: '9-12',
      selectIndex: 6
    }, {
      name: '12小时以上',
      icon: '',
      value: '12',
      selectIndex: 7
    }]
  }]
}, {
  name: '电池电量',
  icon: '',
  value: '',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '20%以下',
      icon: '',
      value: '20%',
      selectIndex: 8
    }, {
      name: '50%以下',
      icon: '',
      value: '50%',
      selectIndex: 9
    }, {
      name: '50%以上',
      icon: '',
      value: '50%',
      selectIndex: 10
    }]
  }]
}, {
  name: '流量',
  icon: '',
  value: '',
  showTabHeader: false,
  defaultIcon: '',
  selectIcon: '',
  selectIndex: 0,
  tabs: [{
    icon: '',
    name: '',
    selectIndex: 0,
    detailList: [{
      name: '100b',
      icon: '',
      value: '100b',
      selectIndex: 11
    }, {
      name: '100kb',
      icon: '',
      value: '100kb',
      selectIndex: 12
    }, {
      name: '100mb',
      icon: '',
      value: '100mb',
      selectIndex: 13
    }]
  }]
}, ]
